//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileExportInvoice
    {
        public int Id { get; set; }
        public int MobileUserId { get; set; }
        public System.DateTime DocDate { get; set; }
        public int DocNo { get; set; }
        public string DocName { get; set; }
        public string Active { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    }
}
