//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileComTier
    {
        public int Id { get; set; }
        public string TierName { get; set; }
        public string TierColor { get; set; }
        public double ComBahtFrom { get; set; }
        public Nullable<double> ComBahtTo { get; set; }
        public double ComPercentage { get; set; }
        public string Active { get; set; }
    }
}
